"""initial schema: devices readings usage_alerts settings

Revision ID: dca9189a5297
Revises: 
Create Date: 2026-09-12 17:34:07.716759+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dca9189a5297'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('room', sa.String(length=60), nullable=False),
    sa.Column('nominal_watts', sa.Float(), nullable=False),
    sa.Column('standby_watts', sa.Float(), nullable=False),
    sa.Column('duty_cycle', sa.Float(), nullable=False),
    sa.Column('cycle_minutes', sa.Float(), nullable=False),
    sa.Column('spike_probability', sa.Float(), nullable=False),
    sa.Column('jitter_pct', sa.Float(), nullable=False),
    sa.Column('is_on', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_watts', sa.Float(), nullable=False),
    sa.Column('last_reading_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_name'), 'devices', ['name'], unique=True)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('household_budget_watts', sa.Float(), nullable=False),
    sa.Column('daily_budget_kwh', sa.Float(), nullable=False),
    sa.Column('z_threshold', sa.Float(), nullable=False),
    sa.Column('baseline_window_minutes', sa.Integer(), nullable=False),
    sa.Column('min_baseline_samples', sa.Integer(), nullable=False),
    sa.Column('max_on_minutes', sa.Float(), nullable=False),
    sa.Column('alert_cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('tick_seconds', sa.Float(), nullable=False),
    sa.Column('simulator_running', sa.Boolean(), nullable=False),
    sa.Column('price_per_kwh', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('watts', sa.Float(), nullable=False),
    sa.Column('is_on', sa.Boolean(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readings_device_id'), 'readings', ['device_id'], unique=False)
    op.create_index('ix_readings_device_ts', 'readings', ['device_id', 'ts'], unique=False)
    op.create_index('ix_readings_ts', 'readings', ['ts'], unique=False)
    op.create_table('usage_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('rule', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('baseline', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('deviation', sa.Float(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_created_at', 'usage_alerts', ['created_at'], unique=False)
    op.create_index('ix_alerts_device_rule', 'usage_alerts', ['device_id', 'rule'], unique=False)
    op.create_index(op.f('ix_usage_alerts_created_at'), 'usage_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_alerts_device_id'), 'usage_alerts', ['device_id'], unique=False)
    op.create_index(op.f('ix_usage_alerts_rule'), 'usage_alerts', ['rule'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_alerts_rule'), table_name='usage_alerts')
    op.drop_index(op.f('ix_usage_alerts_device_id'), table_name='usage_alerts')
    op.drop_index(op.f('ix_usage_alerts_created_at'), table_name='usage_alerts')
    op.drop_index('ix_alerts_device_rule', table_name='usage_alerts')
    op.drop_index('ix_alerts_created_at', table_name='usage_alerts')
    op.drop_table('usage_alerts')
    op.drop_index('ix_readings_ts', table_name='readings')
    op.drop_index('ix_readings_device_ts', table_name='readings')
    op.drop_index(op.f('ix_readings_device_id'), table_name='readings')
    op.drop_table('readings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_devices_name'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
